In [95]:
import torch 
print(torch.__version__)

2.8.0+cu128


In [96]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU : {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available")

GPU is available
Using GPU : NVIDIA GeForce RTX 4050 Laptop GPU


In [97]:
#creating tensors in pytorch
a = torch.empty(2,3)
a

tensor([[5.7041e-19, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])

In [98]:
type(a)

torch.Tensor

In [99]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [100]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [101]:
b = torch.rand(2,3)

In [102]:
torch.manual_seed(22)
c = torch.rand(2,3)

In [103]:
torch.manual_seed(22)
torch.rand(2,3)

tensor([[0.3659, 0.7025, 0.3104],
        [0.0097, 0.6577, 0.1947]])

In [104]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [105]:
a.shape

torch.Size([2, 3])

In [106]:
torch.empty_like(a)

tensor([[4.2928e-19, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [107]:
torch.zeros_like(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [108]:
torch.rand_like(a)

tensor([[0.9506, 0.6887, 0.8174],
        [0.7575, 0.7492, 0.6874]])

In [109]:
torch.relu(c)

tensor([[0.3659, 0.7025, 0.3104],
        [0.0097, 0.6577, 0.1947]])

In [110]:
device =torch.device('cuda')

In [111]:
torch.rand((2,3), device= device)

tensor([[0.8868, 0.5567, 0.9317],
        [0.0299, 0.2426, 0.1462]], device='cuda:0')

In [112]:
a1 = a.flatten()
b = b.flatten()

In [113]:
torch.dot(a1,b)

tensor(1.4626e-19)

In [114]:
a.permute(1,0).shape

torch.Size([3, 2])

In [115]:
import numpy as np

In [116]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [117]:
b = a.numpy()
b

array([1, 2, 3])

In [124]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

w = torch.tensor(1.0)
b = torch.tensor(0.0)

In [ ]:
def binary_cross_entropy_loss(prediction, target):
    epsilon = 1e-8
    prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
    return -(target * torch.log(prediction) + (1 - target) + torch.log(1 - prediction))

In [135]:
z = w * x + b
y_pred = torch.sigmoid(z)

loss = binary_cross_entropy_loss(y_pred, y)

In [136]:
loss

tensor(5.7012)

In [154]:
dloss_dy_pred = (y_pred - y)/(y_pred * (1 - y_pred))

dy_pred_dz = y_pred * (1 - y_pred)

dz_dw = x
dz_db = 1

dl_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dl_db = dloss_dy_pred * dy_pred_dz * dz_db

In [155]:
print(dl_dw)
print(dl_db)

tensor(6.6918, grad_fn=<MulBackward0>)
tensor(0.9988, grad_fn=<MulBackward0>)


In [146]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [147]:
w

tensor(1., requires_grad=True)

In [148]:
b

tensor(0., requires_grad=True)

In [149]:
z = w * x - b
z

tensor(6.7000, grad_fn=<SubBackward0>)

In [150]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [151]:
loss = binary_cross_entropy_loss(y_pred,y)

In [152]:
loss.backward()

In [156]:
print(w.grad)
print(b.grad)

tensor(6.6918)
tensor(-0.9988)
