In [2]:
import torch 
print(torch.__version__)

2.8.0+cu128


In [3]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU : {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available")

GPU is available
Using GPU : NVIDIA GeForce RTX 4050 Laptop GPU


In [36]:
#creating tensors in pytorch
a = torch.empty(2,3)
a

tensor([[2.1227e-17, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [5]:
type(a)

torch.Tensor

In [6]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [19]:
b = torch.rand(2,3)

In [21]:
torch.manual_seed(22)
c = torch.rand(2,3)

In [10]:
torch.manual_seed(22)
torch.rand(2,3)

tensor([[0.3659, 0.7025, 0.3104],
        [0.0097, 0.6577, 0.1947]])

In [11]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
a.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(a)

tensor([[1.2166e-23, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [16]:
torch.zeros_like(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [18]:
torch.rand_like(a)

tensor([[0.2564, 0.0672, 0.9066],
        [0.9175, 0.4236, 0.7978]])

In [25]:
torch.relu(c)

tensor([[0.3659, 0.7025, 0.3104],
        [0.0097, 0.6577, 0.1947]])

In [26]:
device =torch.device('cuda')

In [28]:
torch.rand((2,3), device= device)

tensor([[0.4188, 0.2698, 0.8995],
        [0.4061, 0.1675, 0.3022]], device='cuda:0')

In [33]:
a1 = a.flatten()
b = b.flatten()

In [34]:
torch.dot(a1,b)

tensor(1.2425e-23)

In [38]:
a.permute(1,0).shape

torch.Size([3, 2])

In [39]:
import numpy as np

In [41]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [43]:
b = a.numpy()
b

array([1, 2, 3])