In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [2]:
df = pd.read_csv("http://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [10]:
df.drop(columns=['Unnamed: 32'], inplace=True)

In [11]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [26]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [27]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [28]:
y_train

217    B
428    B
60     B
133    B
19     B
      ..
169    B
392    M
426    B
399    B
288    B
Name: diagnosis, Length: 455, dtype: object

In [29]:
encoder = LabelEncoder()
y_train =   encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [30]:
y_train

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,

In [31]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [32]:
x_train_tensor.shape

torch.Size([455, 30])

In [33]:
x_test_tensor.shape

torch.Size([114, 30])

In [74]:
class my_simple_nueral_network:
    
    def __init__(self, x):

        self.weights =torch.rand(x.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, x):
        z = torch.matmul(x, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        loss = (y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss



In [75]:
learning_rate = 0.1
epochs = 25

In [76]:
model =my_simple_nueral_network(x_train_tensor)
model.weights

tensor([[0.7149],
        [0.3238],
        [0.8236],
        [0.6815],
        [0.4376],
        [0.8478],
        [0.0287],
        [0.1539],
        [0.2549],
        [0.3671],
        [0.4534],
        [0.9031],
        [0.8016],
        [0.0092],
        [0.0681],
        [0.0417],
        [0.8513],
        [0.9797],
        [0.5725],
        [0.1197],
        [0.4464],
        [0.8162],
        [0.3918],
        [0.0792],
        [0.1427],
        [0.7803],
        [0.6383],
        [0.9733],
        [0.8768],
        [0.0301]], dtype=torch.float64, requires_grad=True)

In [77]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [78]:
for epochs in range(epochs):
    y_pred = model.forward(x_train_tensor)
    
        
    loss = model.loss_function(y_pred, y_train_tensor)

    loss.backward()


    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(f"Epochs: {epochs + 1}, loss: {loss.item()}")

Epochs: 1, loss: -3.537096336330839
Epochs: 2, loss: -3.6657471215340958
Epochs: 3, loss: -3.7893628147316183
Epochs: 4, loss: -3.904955228762937
Epochs: 5, loss: -4.010581756591887
Epochs: 6, loss: -4.113444780984596
Epochs: 7, loss: -4.212137050302803
Epochs: 8, loss: -4.306710704780823
Epochs: 9, loss: -4.393086073223606
Epochs: 10, loss: -4.472151264540982
Epochs: 11, loss: -4.542632207047073
Epochs: 12, loss: -4.60734946205404
Epochs: 13, loss: -4.669061240813966
Epochs: 14, loss: -4.726295970996036
Epochs: 15, loss: -4.782278970493649
Epochs: 16, loss: -4.836197205305203
Epochs: 17, loss: -4.887248764783718
Epochs: 18, loss: -4.935205466107817
Epochs: 19, loss: -4.982040924254029
Epochs: 20, loss: -5.028147438449642
Epochs: 21, loss: -5.071860946734078
Epochs: 22, loss: -5.114028592753623
Epochs: 23, loss: -5.15448149024774
Epochs: 24, loss: -5.194098369867862
Epochs: 25, loss: -5.232540929547246


In [79]:
model.weights

tensor([[1.1594],
        [0.5801],
        [1.2826],
        [1.0980],
        [0.7179],
        [1.3509],
        [0.5598],
        [0.7016],
        [0.5310],
        [0.4877],
        [0.7728],
        [0.9332],
        [1.1242],
        [0.2870],
        [0.1273],
        [0.4042],
        [1.1728],
        [1.4090],
        [0.6010],
        [0.3626],
        [0.9184],
        [1.0906],
        [0.8757],
        [0.5067],
        [0.4558],
        [1.2339],
        [1.1436],
        [1.5513],
        [1.1469],
        [0.3485]], dtype=torch.float64, requires_grad=True)

In [80]:
model.bias

tensor([-0.0520], dtype=torch.float64, requires_grad=True)

In [90]:
with torch.no_grad():
    y_pred = model.forward(x_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy {accuracy.item()}")

Accuracy 0.5027700662612915
