In [13]:
import torch
import torch.nn as nn

class Model(nn.Module):
    
    def __init__(self, num_features):

        super().__init__()
        self.networks = nn.Sequential(

            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

    def forward(self, features):

        out = self.networks(features)

        return out

In [14]:
features = torch.rand(10,5)

model = Model(features.shape[1])

model(features)

tensor([[0.4151],
        [0.4072],
        [0.4151],
        [0.4151],
        [0.4090],
        [0.4083],
        [0.4089],
        [0.4029],
        [0.4117],
        [0.4151]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.networks.Linear1.weight

Parameter containing:
tensor([[-0.2270,  0.0626, -0.1484,  0.1367, -0.3934],
        [ 0.2772,  0.4303,  0.0917,  0.1214, -0.3239],
        [ 0.3156, -0.2763,  0.0282,  0.1239, -0.1773]], requires_grad=True)

In [11]:
model.Linear1.bias

Parameter containing:
tensor([-0.0526, -0.1921,  0.1280], requires_grad=True)

In [5]:
!pip install torchinfo

In [12]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00