In [1]:
import torch
print(torch.__version__)

2.8.0+cu128


In [ ]:
# Check if CUDA (GPU support) is available
if torch.cuda.is_available():
    print("CUDA is available. GPU can be used.")
    print(f"Number of available GPUs: {torch.cuda.device_count()}")
    print(f"Current GPU device: {torch.cuda.get_device_name(0)}")
else:
    print("CUDA is not available. Using CPU.")

CUDA is available. GPU can be used.
Number of available GPUs: 1
Current GPU device: NVIDIA GeForce RTX 4050 Laptop GPU


In [9]:
#using torch to create a empty tensor
t =torch.empty(2,3)

In [11]:
# checking for type
type(t)

torch.Tensor

In [ ]:
#creating a tensor with zeros values
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#creating a tensor with ones values
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# Creating a tensor with random values
torch.rand(2,3)

tensor([[0.8393, 0.3355, 0.9565],
        [0.9293, 0.6038, 0.3125]])

In [15]:
#using seed to generate same random values
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [16]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
#other way to create tensor like arrange
torch.arange(0,11,2)

tensor([ 0,  2,  4,  6,  8, 10])

In [21]:
#using linespace
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [22]:
#using eye
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [23]:
#using full
torch.full((2,3),9)

tensor([[9, 9, 9],
        [9, 9, 9]])