In [1]:
import torch
print(torch.__version__)

2.8.0+cu128


In [2]:
# Check if CUDA (GPU support) is available
if torch.cuda.is_available():
    print("CUDA is available. GPU can be used.")
    print(f"Number of available GPUs: {torch.cuda.device_count()}")
    print(f"Current GPU device: {torch.cuda.get_device_name(0)}")
else:
    print("CUDA is not available. Using CPU.")

CUDA is available. GPU can be used.
Number of available GPUs: 1
Current GPU device: NVIDIA GeForce RTX 4050 Laptop GPU


In [3]:
#using torch to create a empty tensor
t =torch.empty(2,3)

In [4]:
# checking for type
type(t)

torch.Tensor

In [5]:
#creating a tensor with zeros values
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
#creating a tensor with ones values
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# Creating a tensor with random values
torch.rand(2,3)

tensor([[0.2887, 0.6186, 0.4240],
        [0.6149, 0.6681, 0.8681]])

In [8]:
#using seed to generate same random values
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
#other way to create tensor like arrange
torch.arange(0,11,2)

tensor([ 0,  2,  4,  6,  8, 10])

In [11]:
#using linespace
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [12]:
#using eye
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [13]:
#using full
torch.full((2,3),9)

tensor([[9, 9, 9],
        [9, 9, 9]])

In [15]:
#tensor shape
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [23]:
#creating empty tensor like x
torch.empty_like(x)

tensor([[              0,       478728352,       488381184],
        [125859221525744,               1,               6]])

In [24]:
#creating zeros tensor like x
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [25]:
#creating ones tensor like x
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [26]:
#creating random tensor like float x
torch.rand_like(x.float())

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [27]:
#tensor datatype
x.dtype

torch.int64