In [1]:
import torch 

In [8]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [9]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32).to(device)
my_tensor.dtype

torch.float32

In [10]:
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

In [11]:
my_tensor.device

device(type='cuda', index=0)

In [13]:
x = torch.empty(2,3)
x

tensor([[1.5695e-43, 1.3593e-43, 1.6255e-43],
        [1.3873e-43, 1.4574e-43, 1.0510e-43]])

In [15]:
x = torch.zeros(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [17]:
x = torch.rand(2,3)
x

tensor([[0.0242, 0.5361, 0.1578],
        [0.8415, 0.7389, 0.4341]])

In [18]:
x = torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [19]:
x = torch.eye(2,3)
x

tensor([[1., 0., 0.],
        [0., 1., 0.]])

In [25]:
x = torch.arange(start=0, end=9, step=0.1)
x

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000, 1.1000, 1.2000, 1.3000, 1.4000, 1.5000, 1.6000, 1.7000,
        1.8000, 1.9000, 2.0000, 2.1000, 2.2000, 2.3000, 2.4000, 2.5000, 2.6000,
        2.7000, 2.8000, 2.9000, 3.0000, 3.1000, 3.2000, 3.3000, 3.4000, 3.5000,
        3.6000, 3.7000, 3.8000, 3.9000, 4.0000, 4.1000, 4.2000, 4.3000, 4.4000,
        4.5000, 4.6000, 4.7000, 4.8000, 4.9000, 5.0000, 5.1000, 5.2000, 5.3000,
        5.4000, 5.5000, 5.6000, 5.7000, 5.8000, 5.9000, 6.0000, 6.1000, 6.2000,
        6.3000, 6.4000, 6.5000, 6.6000, 6.7000, 6.8000, 6.9000, 7.0000, 7.1000,
        7.2000, 7.3000, 7.4000, 7.5000, 7.6000, 7.7000, 7.8000, 7.9000, 8.0000,
        8.1000, 8.2000, 8.3000, 8.4000, 8.5000, 8.6000, 8.7000, 8.8000, 8.9000])

In [26]:
x = torch.linspace(start=0.1, end=1, steps=99)
x

tensor([0.1000, 0.1092, 0.1184, 0.1276, 0.1367, 0.1459, 0.1551, 0.1643, 0.1735,
        0.1827, 0.1918, 0.2010, 0.2102, 0.2194, 0.2286, 0.2378, 0.2469, 0.2561,
        0.2653, 0.2745, 0.2837, 0.2929, 0.3020, 0.3112, 0.3204, 0.3296, 0.3388,
        0.3480, 0.3571, 0.3663, 0.3755, 0.3847, 0.3939, 0.4031, 0.4122, 0.4214,
        0.4306, 0.4398, 0.4490, 0.4582, 0.4673, 0.4765, 0.4857, 0.4949, 0.5041,
        0.5133, 0.5224, 0.5316, 0.5408, 0.5500, 0.5592, 0.5684, 0.5776, 0.5867,
        0.5959, 0.6051, 0.6143, 0.6235, 0.6327, 0.6418, 0.6510, 0.6602, 0.6694,
        0.6786, 0.6878, 0.6969, 0.7061, 0.7153, 0.7245, 0.7337, 0.7429, 0.7520,
        0.7612, 0.7704, 0.7796, 0.7888, 0.7980, 0.8071, 0.8163, 0.8255, 0.8347,
        0.8439, 0.8531, 0.8622, 0.8714, 0.8806, 0.8898, 0.8990, 0.9082, 0.9173,
        0.9265, 0.9357, 0.9449, 0.9541, 0.9633, 0.9724, 0.9816, 0.9908, 1.0000])